language: ruby
rvm:
- 2.6.0
before_script:
- bundle install
- bin/rails db:create
- bin/rails db:migrate
deploy:
  provider: heroku
  api_key:
    secure: SdXD6LRc3TazWP5CoK8uaP1lHwnKlAkjoETBOrvjwOkSDzdTfoFaYl9rmz3ak3KcLSItZ9KDjR+eW/IzNXOQVpxbweFrtLwdI6EvzHZHUd7OpD8dc0lYUwlW6zbQAjMIMplIcbzIoZ3ZURv/LwMgytPUimh3ByJyECS4tZymT/IkOumkGta7eXfY+OoCLv5CaBXhDWdCyz5jTCAY/17WDGDZmwGgDsnNIt+TawW7GcqHWiKAQY1r/WI2nk6my7SoI2eYQX5diyehHGlDSs2faE6qOLKoAal4/EJW5CjpfYm0EkhA1xrIy31qb4eTDZFqzwnn7s0QHBN9LJ4Ilc4pG955FA4V1ZiJ73YRg5c9Yi+cWVhuicuCUdbKFI4+LTpxwThA+JmYI/lYYHvmGq4tSTMexf8qbSzF3Jom2funzWn/SK00GaKLmCQhowhbW/a9RPibAWoNO0IYa80rZsw2aQI+m6eykGcvh9h3wFclbktLZv76lQJndZiIJMmhdRN9dg80y6hYMmHRoRsG5pIIjqR0JcqmZY8JeTAoofi9CmblFyFlqZG8LdLw0EKKSmA6v4CP0PSTwxlOlXRyzz4lc1Nzj7su0f81nKWZRjfdA1Olhpg8gasY8ijLb4us1niAXgwtHBWFKMyaZd3rtbrk2UQv+OW5rJIyku/3a+zCDSY=
  on:
    repo: Hannah-Frost/acebook-Isambard
script:
- bundle exec rspec
