language: ruby
rvm:
- 2.6.0
before_script:
- bundle install
- bin/rails db:create
- bin/rails db:migrate
deploy:
  provider: heroku
  api_key:
    secure: bFCkZrszB8VZF7VlBsHrYINzF/3J+OvGfl6FsfshYqSGeISH9DPyEZwA5xR7CRnWj0GKcedCai+DoxHgStKB00wZ9wYoiJIs3d1ARUeoY1/UMMMfKvxOBHLkL2Gm2LyE5rLu7mCG94zRfWvOPgZSlr5Z4qQCFqUbvfftaQoDLkiuCcqRczoKdVUK1A9jwPz2eyPSD0LgV3qLoBN20zM8czS+NTtAMjjq+DhYAmT4XzHE0BESoL2HGR8CZ1R0lS/ksm1p4GiBDx0qO0tj+h2t8r4ri6yWHNntP9k8tLqA65KZzmt3U8ot/SY7tPAH2rYHUvHAKUAGszL3NFL0dThzXhOOF+O67d1E78V15YnVmIvDRYCGq2rgyhT4gwcyHnAhjcjcUf3jfOp8ToHsRPaJ8BQ4nBtl+QrCzliSFVBQz7SmkRGSjYwBZuOiXGyBtb+CrIvh6sZ0o6dfVypevCItLdiuNBf/EfDARw2Wz7QusWAN6HPWkNtWBzPeiIVJ2XiLFC93IpsIAzBgJF1xGI4w5Trt5r9aSsES8mT7ZNxkhG3iLMDkGIT9brXNAmFOWf5/AJFFvDoO4/2AH36BQRu9U5cKPweshdaWEgQJqwUlHBH4cguOdQ5qRe75AzAkKShegJStEKOiOyZ2iOvIfCPOgv7quqCaC6cryJ+8DvCDKhA=
  app: acebook-isambard
  on:
    repo: Hannah-Frost/acebook-Isambard
script:
- bundle exec rspec
