language: ruby
rvm:
 - 2.6.0

# Must run specific commands to make Travis follow the installation process before running tests.
before_script:
- bundle install
- bin/rails db:create
- bin/rails db:migrate

deploy:
  provider: heroku
  api_key:
    secure: "aIcSZ0oZj87Pyo8q55McQi/sJDGRGMiNXMeNT1ofcnOlPAMbdYuEc4+9YJ+13OQmYEp4y6qandjGJ8ZScpydQ2gXGTMPOHzuYDhPurBymoM1IZSTtV7q0amMt1pqvHWZSMkz2vtc8Ma5fkt7HggkvSPTP1gUHoLcAg6tXOUxiTnoM+1rNRUawdLKmJxSj5jIJoxy/NOzTNpJpu6pzlDUvaxoXCmeD7IuREfOEyekQT0XXZj9fK3S2yxwMdBKgL3C1/2gpuUXumSS8sFu1TEeZxquYTuhnub4pGKc/CSgVdXZoErT83iDdJFioDh3PiAdBKP05fkabz5feWCxxm8qFsAZSidu2UrFm7pmN+nCM+aLKOT4HvfeZ/yw9drdP9d6QR7V3d/JmvlCPIYwb860bGd2tA82PmddYN5eDNqd6BlPYYR8ZAxKockOHHL7CXncNC+O4lW1B3C6+hWu+41xzy5I/bHj6qlnl2aQSggHoR3m6AuxrMu/yCz/9ZYg+pg1f6CjXWuEku3UWLNW9zKdL/VZI21/X8GXSTnMwgtCJNAvyrP1Ntmf0KxJvFcrRrwbO/BxOFKoprAH3aPWavvoXdRUlr7ucX+imGiccU/w44m/ImsJTJSrjp1vFiM+suLmasvBX2VagiB2BQDRraPgfchvOtHPgGRR9SDoFEriIn0="
  app: acebook-isambard
  on:
    repo: Hannah-Frost/acebook-Isambard

# Now the test command can be run successfully. :)
script:
- bundle exec rspec
