language: ruby
rvm:
- 2.6.0
before_script:
- bundle install
- bin/rails db:create
- bin/rails db:migrate
deploy:
  provider: heroku
  api_key:
    secure: pe7n94oTjuO5CCNfNQASIDmFKtNiux8bZh8dEdXKoXK/iXUV9ms1qHVOHfj3wSRiwyM1Xx/MZvHGzYnr+VizpdVoEBcvM7nComwhsx16J+izh2/njmMpuoylgGyJ18PQJnIcsfMTaBnofS0VBRcxfe5WULbhTEQg60NO5Sfn66whUM5p6XieZMsig6Lp6savu0WtqKQYIQJTsJlWPrqufK0+w7WsH9ItT6V9vyz8llI1GF27M5Gy9DdwZg2Q8MtHnrISrrTS1oxtH2ixH5MGXl5GCXZ8jw2t23/sVwRjrsxO3UFl2yUTdiv9VAk2yHQKYq7cG5ElNftvP5MjYEK57AW2VhnhRxWfGFn0dqJ/RltOlqJL2UW0GZzjlPaXXolWC9Rl5VObkXogAgEzCielG2ysHFqXR0zw5pPL+ikYZT7p/sQXEThaoNgnpUeWqnP4t2HvwdPosFGkOhs0LwaDAAOB28PWsSuh4NR2MMVGPVjaIjxzpqhDjSB8xBYetGK9WPYJv7XteVx8X84xDgEuNgJwmDtUMozd3jXXQyELhGlwWwbt8IFOFw7y7N/S3pWQI8zF0SogEuS6z6oGr9JK9S5uTrjo2YUlghpEIP5uiJmKwyHVqxVAxeAKHwnaKznvYBSj87OpzMifwFpcPgecqxC9oSXB1igKsx9uSosW8LM=
  on:
    repo: Hannah-Frost/acebook-Isambard
script:
- bundle exec rspec
