language: ruby
rvm:
- 2.6.0
before_script:
- bundle install
- bin/rails db:create
- bin/rails db:migrate
deploy:
  provider: heroku
  api_key:
    secure: KHD4cRHukpaXMflAJJGg5+8vmgId7/r0fz8Veex5wob8uDI0SdEdNhf4sqw0Dxzo1NUMgBsNzePSFACEtbqU4atIhsQglt9zt++Pk0yACjPLI2yIzcbK2AvZgONwdJEmvc/+qx7joXQ4Zqy5xybUJ6G4yGvYydKTIRReqw+lTUSnSliPEUGU/gRj5zpZABDRcEjx3qjFcbCha29tJPIfiPshkG8w5Q2oTBBfnsvTyn9plrfMFP0CqAJF4pIKXbIme8hG9rVLb9+JLYkmXdVJMWS288kL1u95YHVKmtgA0Kd3/Uvemz8ae9IdHsyyVsAYUjc4xbq/jqMPNclh8Y0l2vn+mD14Btp548jbVcCJ4UPKtkLALzXs3+/A7XVZ+7EW9kMLgHjdBG7rwObq09xDNoTG7BkBKVFnjn993M3osZQU/PnCnyLARL9NrCUIr7SxmFxlnMKaRtL3qnxgDeF5jccBNiym2I/0YTld7IVHeDYB27pux+tLBBTnrzUT0NdgyU7NdOYnAIVGTyXrorKPahffVoj+wjxNggxuzDpNykh5nquvaNs/oMEPXIObguLnM2ybGJDggNuQywBrfTOmEk38u43bbcNWx91TuCBcYnEZmvQVZkVEF2KZLrSbBIafOE9kH/Z3+pQd8uo9uKCSYF8l2qqcVu4TzoHIOosqHMM=
  app: acebook-isambard
  on:
    repo: Hannah-Frost/acebook-Isambard
script:
- bundle exec rspec
