language: ruby
rvm:
- 2.6.0
before_script:
- bundle install
- bin/rails db:create
- bin/rails db:migrate
deploy:
  provider: heroku
  api_key:
    secure: AlTC1/aIVOYp7d46HShSWYgSoIritaKHYa0y+B2yeYrcDDm++PxAIkUpli2lnZAnxWWBY4WNj8IM4Ty0HBo7zzB/CXPBosr0juCdawJ5Z7tvgd9UhCzvscUIu6n8e6Uj5I22KMylv52us9KBf57rHsJekCFlQj5f62X4PW8Z4+qRGCH8MESdlUz7SNOcndNPzQbBWKLIC81Tysi73taAn155F8Kpoj5p522fzAZcrAYazk/wNw7PQg/H5UOgfuutQQ6NIZDjReva9AW5Xl70aTPDo7fm4hRQPZUna6kqyqggLkVCkf7Y86PgZEEzXgeWWT3nsBXmYvvBU8uQjDg8Hhdhb8XMukd9tmz9Bile8CR8Aq2D7gkJMqXHurTOBVl6b6zYPFjih83jaRFYP/hfQDt+fiwl/CkwwwhCBNNPMw/2wLfGatdjCNpliGgTtAMzuACIc4MB1zNRJPbT17nstAOaJRv5kKdYxaCmevA6G917VdKBcwiyjeAEeYNuNtvrbuAz4lddgtHIkoJBalU0QZ83pyKlZo86UlkWhCo/PgjJMMXSe8vBQL1iatmaOJsdnTHDsIZWlpoayThtKYNq89u7To+pKbpHDOqdBlmVKPFMrmG9fKnwLmsgCSAuEFiEnC/cAs35FdlQ7gjT+s0cTav9de8yuzwM1XtZUWgWcPI=
  app: acebook-isambard
  on:
    repo: Hannah-Frost/acebook-Isambard
script:
- bundle exec rspec
